### ISSUE TITLE
Question about configuring network traces with bandwidth information

### ISSUE THREAD

**Issue by jialianchen** [clarkzjw/mmsys24-starlink-livestreaming#3]
Thank you for your open source work which has been very helpful for newcomers in this research area!

I have some questions about extending the system to work with new network traces similar to classic datasets like FCC and Norway. I want to test with custom network traces but I'm unclear about where to make the modifications.

In docker-compose-emulation.yaml, I only found:
```yaml
nginx:
  image: clarkzjw/dashjs-nginx:emulation
  build:
    context: .
    dockerfile: Dockerfile-nginx-emulation
  container_name: dashjs-nginx
  volumes:
    - ./runner/trace/isl-trace.csv:/trace/trace.csv
```

The isl-trace.csv only contains columns for "since", "relative_seconds", and "rtt", but no bandwidth settings. Could you please clarify:

1. Where is the bandwidth trace configured in the system?
2. What's the proper way to add custom network traces with bandwidth information?

Thank you very much for your help!
